### ISSUE TITLE
Example use case location via cdn or static .mmdb file

### ISSUE THREAD

**Issue by jeroenvermeiren1984** [AndyButland/UmbracoPersonalisationGroupsCore#11] opened 2023-11-27 08:15 UTC
Hi,

My apologies to fire this as an issue but I'm a bit stuck on how to properly use this package working based on location/country.
Ik can however get it to work with a simple check (like for example day of the week etc) like provided in the example.

But I'm a bit confused on how to get this to work on location.
Is it perhaps possible to provide a simple example on how to use this combined with either a cdn or a static file (/umbraco/Data/PersonalisationGroups/GeoLite2-Country.mmdb). I already tried it with a static GeoLite2-Country.mmdb but nothing seems to happen.

Thanks in advance. And apologies upfront if this is not the correct channel as this is not really "an issue".

**Comment by AndyButland** [comment] 2023-11-27 12:40
Perfectly fine to ask here. It's been a little while since I've looked at this feature but I can certainly verify the behaviour and post an example.  Will probably be at the weekend that I'll get to it though.

Meantime could you share what version of Umbraco CMS and the Personalisation Groups package you are using please?

**Comment by jeroenvermeiren1984** [comment] 2023-11-30 12:53
Hi Andy,

Super and thank you for willing to look into it and provide an example! Locally I'm working on Umbraco version 12.3.0.
However the production environment is currently locked at version version 10.1.0 so it basically needs to work on both versions eventually. As for the version of the package i'm working with the latest version I believe which is 3.2.8.

In my template for my test type I currently do a simple check:

@Umbraco.MatchesGroup(GroupMatchingService, "test group") 

Where "test group" si my defined test group and currently does a check by Country:

![Screenshot 2023-11-30 at 13 43 19](https://github.com/AndyButland/UmbracoPersonalisationGroupsCore/assets/97600073/fa0a7405-0272-4ee2-a864-d56a0fc5b94d)

Based on the condition it should return "True" (visitor is not located in Andorra, Albania > I'm located in Belgium) but it always shows "False". I'm currently using a static GeoLite2-Country.mmdb file to check.

![Screenshot 2023-11-30 at 13 49 45](https://github.com/AndyButland/UmbracoPersonalisationGroupsCore/assets/97600073/37b9ce9e-d9a6-4948-a958-f0c143172ba6)


If I change the condition to a simple "day of the week" check it works perfectly tough and shows either true/false if it matches the current day. So something is either not well configured or maybe something wrong with the mmdb file but I can't say what tbh. So any help is very welcome atm. Sorry I'm kind of an Umbraco nooby atm :)

If you need more information from me please ask, I'm happy to provide and thanks again for taking the time to investigate.

Kind regards

Jeroen

**Comment by jeroenvermeiren1984** [comment] 2023-12-07 12:14
Hi Andy,

I tried your suggested solution but I still always get "False" back for the conditional check whether the user is located in "Belgium".

I tried with both IPv6 and IPv4 value for the TestFixedIp as suggested generated from the url https://www.whatismyip.com/. (seems also be the same data as maxmind https://www.maxmind.com/en/geoip-databases)
But they are both giving me the same result atm. (always False)

<img width="850" alt="Screenshot 2023-12-07 at 12 05 34" src="https://github.com/AndyButland/UmbracoPersonalisationGroupsCore/assets/97600073/e5d65fd0-3e76-4fb5-8f24-99bf6f3930cd">


    "PersonalisationGroups": {
        "TestFixedIp": "84.192.48.72"
      }

OR

    "PersonalisationGroups": {
        "TestFixedIp": "2a02:1810:9400:ae00:c3c:62:72d3:a0a"
      }

<img width="351" alt="Screenshot 2023-12-07 at 12 09 59" src="https://github.com/AndyButland/UmbracoPersonalisationGroupsCore/assets/97600073/657eaf92-c500-4cce-83f3-449d920aad88">


My group is called 'Test group' with the following condition for the template:

<img width="738" alt="Screenshot 2023-12-07 at 12 41 50" src="https://github.com/AndyButland/UmbracoPersonalisationGroupsCore/assets/97600073/f313472f-b85c-45ad-a53d-bb3f4c4cabc9">

and inside the content template:

@Umbraco.MatchesGroup(GroupMatchingService, "test group")

So I'm not sure why it isn't working for me. Could you perhaps try the same and see what results you get with it? Thank you so much for your time/investigation

Kind regards

Jeroen

**Comment by AndyButland** [comment] 2023-12-08 10:37
I've followed what you've done here and it seems OK for me.  I think the problem is that you have the configuration in the wrong place.  The `PersonalisationGroups` element should be a sibling of `Umbraco:CMS`, not a child.  Like this:

```
  "Umbraco": {
    "CMS": {
      ...
    },
    "PersonalisationGroups": {
      "DisablePackage": false,
      "TestFixedIp": "84.192.48.72",
      "DisableUserActivityTracking": false
    }
  }
```

**Comment by AndyButland** [comment] 2024-03-09 14:42
Closing this now since no further discussion.

**Closed by AndyButland** 2024-03-09 14:42 UTC
